name: antd_flutter_mobile
description: "Antd Flutter implementation, zero dependencies, ultra-lightweight (only 200kB), 50+ components, complete Antd Token system implementation."
version: 5.0.6-alpha.1
homepage: https://antd-flutter.vercel.app/
repository: https://github.com/OpenSourceNoCode/antd-flutter
topics:
  - antd
  - design-system
  - ui-components
  - form
  - lightweight

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  #dart run icon_font_generator:generator
  icon_font_generator: ^4.0.0

icon_font:
  input_svg_dir: "assets/icons"
  output_font_file: "assets/fonts/icons.otf"

  output_class_file: "lib/components/icon/index.dart"
  class_name: "AntdIcons"
  package: antd_flutter_mobile
  format: true

  font_name: "AntdIcon"
  normalize: true
  ignore_shapes: true
  recursive: true
  verbose: false

flutter:
  fonts:
    - family: AntdIcon
      fonts:
        - asset: assets/fonts/icons.otf

